[build]
  command = "npm run build"
  publish = ".next"

[dev]
  command = "npm run dev"
  port = 3000

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  included_files = ["node_modules/.prisma/client/**/*"]

[build.environment]
  NODE_VERSION = "24"
  NPM_FLAGS = "--legacy-peer-deps"
